on:
    push:
      paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']
      tags:
        - "**"
      branches:
        - 'integration'
        - 'release/version*'
        - 'docker-images'
    workflow_dispatch:
jobs:
  call-reusable-workflow:
    uses: nationalsecurityagency/datawave-accumulo-service/.github/workflows/build-image.yaml@docker-images
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      